### ISSUE TITLE
avifの色味がおかしい

### ISSUE THREAD

**Issue by kozakura913** [yojo-art/media-proxy-rs#20]
なんかコントラスト高くない？

**Comment by 1673beta** [comment]
そこまで気になるほどではない気がする。むしろ原神幼女rs.webpのほうが不自然に彩度が高い気がする

**Comment by kozakura913** [comment]
imageで読む時に色空間がBT601に固定されてるのが原因
https://github.com/image-rs/image/pull/2200

**Comment by kozakura913** [comment]
プルリク通らなかったらforkする

**Comment by kozakura913** [comment]
機能テストに便利
https://github.com/link-u/avif-sample-images

**Comment by kozakura913** [comment]
プルリクが通ったのでマージ済のimage crateがリリースされると自動的にこの問題は解消します

**Comment by kozakura913** [comment]
忘れないようにリリースされるまでは開けておく
